### ISSUE TITLE
Conflicts with `goto-address-mode`?

### ISSUE THREAD

**Issue by Yevgnen** [awth13/org-appear#36] opened 2022-01-17 15:21 UTC
The issue seems strange. Using minimum reproducible config below and considering an Org mode buffer with content

```
~abc*~                         # * denotes cursor
#+caption: abc
```

then backward delete three times to delete 'c', 'b' and 'a', the cursor jumps to `*~~`. I would expect `~*~` instead. 

Either disabling `goto-address-mode` or with `(progn (org-appear-mode -1) (setq org-hide-emphasis-markers nil))` the issue is gone. Due to my limited elisp knowledge, I'm not sure whether this is an `org-appear` issue or not.

```el
(setq user-init-file (or load-file-name (buffer-file-name)))
(setq user-emacs-directory (file-name-directory user-init-file))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

(require 'package)
(add-to-list 'package-archives '("tromey" . "http://tromey.com/elpa/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(setq package-user-dir (expand-file-name "elpa/" user-emacs-directory))
(package-initialize)

;; Install use-package that we require for managing all other dependencies
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; A
(add-hook 'text-mode-hook #'goto-address-mode)

;; B
(package-install 'org-appear)
(add-hook 'org-mode-hook #'org-appear-mode)
(setq org-hide-emphasis-markers t
      org-appear-autoemphasis t)
```

Emacs version: `GNU Emacs 27.2 (build 1, x86_64-apple-darwin21.1.0, Carbon Version 165 AppKit 2113) of 2021-11-01`

**Comment by SPFabGerman** [comment] 2022-01-17 15:37
Interessting. I found a very simmilar issue in #34. In fact, the behaviour seems to be exactly the same. I think both issues come from the same cause. (I would have to look at the source code of `goto-address-mode` to confirm this.)
The problems seems to be, that `goto-address-mode` hides the markers, then the user deletes the characters, but after the deletion Emacs places the cursor before the invisible markers, and after that `org-appear` unhides the markers again.

Btw: as far as my testing showed, the caption is irrelevant.

**Comment by awth13** [comment] 2022-01-17 15:56
As far as I can tell from the initial testing, this is the intended behaviour of Org mode. With or without `goto-address-mode` enabled, Org mode skips the invisible `~` character when moving the cursor after the last deletion. When `org-appear-mode` is disabled, it does the same.

In addition to that, `goto-address-mode` does not seem to interfere with `jit-lock` in the same way `org-pretty-tables` does in #34.

Maybe I missed something?

P.S. `org-pretty-table` modifications to `jit-lock` seem to linger until the buffer is reloaded, even after `org-pretty-table` is disabled. Maybe that's why you found similar behaviour, @SPFabGerman?

**Comment by Yevgnen** [comment] 2022-01-17 16:03
> Btw: as far as my testing showed, the caption is irrelevant.

@SPFabGerman Without the caption part, I can't reproduce the issue in an `emacs -q` session with the config above. 

That's quite weird...

**Comment by Yevgnen** [comment] 2022-01-17 16:07
> When org-appear-mode is disabled, it does the same.

@awth13 I tested with the above config, and without `org-appear` + `org-hide-emphasis-markers nil`/`goto-address-mode` (to make the marker visible in both ways), the issue seems gone here?

**Comment by awth13** [comment] 2022-01-17 16:10
> I tested With the above config,and without org-appear/goto-address-mode, the issue seems gone here?

What is your Org version?

**Comment by Yevgnen** [comment] 2022-01-18 00:18
Hi, I'm using `Org mode version 9.5.2 (9.5.2-g8d9ca0 @ /Users/User/.emacs.d/straight/build/org/)`

**Comment by awth13** [comment] 2022-01-22 17:05
@Yevgnen, thank you for the input and sorry for the delayed response.

Indeed, testing with Org mode version 9.5.2, I was able to reproduce the behaviour you described. 

With `org-appear` disabled, we observe the intended cursor movement -- the first `~` is skipped when backwards deleting. I would like to emphasise again that this is what Org mode believes is the correct movement. When markers are hidden (`org-hide-emphasis-markers` set to `t`), the cursor should skip over invisible characters in the buffer.

With `org-appear` enabled but `goto-address-mode` disabled, `org-appear` correctly interferes with the intended cursor movement by preventing skipping over the unhidden `~`. 

With both `org-appear` and `goto-address-mode` enabled, the cursor, again, skips over the invisible `~` despite `org-appear` trying to make it visible. This is because `goto-address-mode` adds a fontification function to `jit-lock`, thus disrupting `org-appear` -- a similar issue is described in #34.

While explaining exactly why and how this happens is beyond my current understanding of `jit-lock-mode`, I can confidently say that the issue cannot be resolved without fundamental changes to the way `org-appear` works. Previously in [a Reddit discussion](https://www.reddit.com/r/emacs/comments/p9yjgq/turn_off_fontlock_under_cursor/), it has been noted that `org-appear` and similar packages fight against the Emacs display engine instead of working with it; this is another example of why that assessment is true. Right now, unfortunately, I don't have any solutions in mind.

**Comment by Yevgnen** [comment] 2022-01-23 05:43
@awth13 Thanks for digging into this! After a quick look I haven't fully understood yet but I will definitely read it again later. 

Recently I made a small [package](https://github.com/Yevgnen/org-modern-bullets.el) and it suffered from the same jit-lock issue when working with `org-appear`. Hopefully we can find a way to solve this!

Also, please take good care of yourself!

**Comment by awth13** [comment] 2022-01-28 04:15
@Yevgnen, thank you for the kind words!

The package looks very interesting. I wonder, though, can't the same be achieved by forcing `org-indent-face` to inherit from `fixed-pitch`, e.g., as described [here](https://zzamboni.org/post/beautifying-org-mode-in-emacs/)? In my current setup, this seems to happen automatically, though I haven't had time yet to explore why.

**Comment by Yevgnen** [comment] 2022-01-28 05:31
@awth13 

Hi, in fact the default `org-indent` already inherits `org-hide` which inherits `fixed-pitch`. This setting works is there are  only `fixed-pitch` and `variable-pitch` chars and short lines in the buffer. 

If the buffer is again mixed with other unicode chars/fonts (which is generally hard to find a suitable font like [Sarasa](https://github.com/be5invis/Sarasa-Gothic) that can handle all ascii and unicode chars and tweaking `face-font-rescale-alist` is generally necessary), or the buffer contains long lines with line wraps, the issue remains. The bullets and the spaces after are not fontified and in my settings they are using a variable-pitch font. One may use packages like `org-superstar`, `org-bullets` to use fancy bullets and get a chance to custom the faces of the bullets, but the unicode bullets are generally have another different width (from the space after them and other chars)...and they don't seems to performance well with my Emacs config.

So I go the naivest way, just to make every 'prefixes' get the same width...I'm not sure whether there's a better way to fix it.

Before: (I use background color to highlight the face)
<img width="857" alt="Screen Shot 2022-01-28 at 1 09 11 PM" src="https://user-images.githubusercontent.com/16749790/151491630-7f1ca07b-ca02-45e9-95be-cde3eabbe8ba.png">

After:
<img width="870" alt="Screen Shot 2022-01-28 at 1 10 05 PM" src="https://user-images.githubusercontent.com/16749790/151491654-ac7465fa-c993-41d9-9d71-d9c3984438cb.png">

**Comment by awth13** [comment] 2022-06-05 00:01
Hi, @Yevgnen! I am sorry for not responding earlier.

I will be closing this issue to merge it with #34 as the underlying issue is the same.

**Closed as not planned by awth13** 2022-06-05 00:01 UTC
