### ISSUE TITLE
`org-appear-autolinks` stop work after the cursor swept org-ref cite link

### ISSUE THREAD

**Issue by HyunggyuJang** [awth13/org-appear#15] opened 2021-04-16 00:11 UTC
Hi, I'm enjoying your endeavour! I think this package is indeed elegant solution both for appearance and explicit for accurate editing.

However, today, I felt some buggy behavior, namely it stops working after it encounters `org-ref` 's cite link: For example, I have `cite:avigadTheoremProvingLean` bibtex site link in the org buffer, and after the cursor laid that cite link, not only for the autolinks feature, but also org-appear as whole stop to work at that buffer.

Here is the typical message from when `org-apear` become panic:
``` text
Error in post-command-hook (org-appear--post-cmd): (wrong-type-argument integer-or-marker-p nil)
Avigad, J., Theorem Proving in Lean, , (), 173 (). 
```

Thanks for reading this issue! 

Best regards,

-- Hyunggyu Jang.

**Comment by awth13** [comment] 2021-04-17 07:27
Hi, @HyunggyuJang!

Thank you for your kind words and thank you for alerting me to the issue! It is now [fixed](https://github.com/awth13/org-appear/commit/f9740dbd1b950c2de592fe0774a515a3b12f649a) so I will close the issue in a minute.

**Comment by HyunggyuJang** [comment] 2021-04-18 11:32
Thanks for your quick reply! 

I can confirm the issue I encountered completely resolved!

Really appreciate this _superb_ package! 

Best regards,

-- **Hyunggyu Jang**

**Closed as completed** 2021-04-18 11:33 UTC

**Comment by mclearc** [comment] 2021-05-16 16:37
It looks like this problem might have returned. I'm noticing that commit `f0e9d53 * Ignore whitespace in elements`  reintroduces the error. 
The previous commit `c3466c4 * @ Don't unhide elements until point is inside` works fine.

**Comment by awth13** [comment] 2021-05-16 19:41
Thank you for the heads up, @mclearc.

The issue is [resolved](https://github.com/awth13/org-appear/commit/9fcf2486e70362d9fbdd40f3eae26ee0c04f13a9) and I took steps to make sure this bug will not be reintroduced in the future.
